### ISSUE TITLE
regex python module install fails

### ISSUE THREAD

**Issue by robbyt** [Valloric/ycmd#1014]
Using MacOS 10.13.14, with Python from Brew:

```
...
[100%] Built target ycm_core
Collecting regex==2018.02.21
Installing collected packages: regex
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/wheel.py", line 216, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 248, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both")
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
WARNING: cannot install the regex module. Unicode will not be fully supported.
```

I am able to install the regex module via `pip3 install regex`

**Comment by puremourning** [comment]
The install didn’t fail. Ycmd should work fine per the warning.

**Comment by puremourning** [comment]
> WARNING: cannot install the regex module. Unicode will not be fully supported.
