### ISSUE TITLE
libclang: crash detected during parsing

### ISSUE THREAD

**Issue by naseer** [Valloric/ycmd#103]
Found with emacs-ycmd - https://github.com/abingham/emacs-ycmd/issues/166

`*ycmd-server*` buffer
```
2015-03-27 15:24:30,892 - INFO - Received completion request
 2015-03-27 15:24:30,892 - DEBUG - Using filetype completion: False
 2015-03-27 15:24:31,222 - INFO - Received completion request
 2015-03-27 15:24:31,223 - DEBUG - Using filetype completion: False
 2015-03-27 15:24:31,251 - INFO - Received completion request
 2015-03-27 15:24:31,253 - DEBUG - Using filetype completion: False
 2015-03-27 15:24:32,034 - INFO - Received completion request
 2015-03-27 15:24:32,035 - DEBUG - Using filetype completion: True
 libclang: crash detected during parsing: {
   'source_filename' : '/local/mnt/workspace/naseer/LA.BF64.1/hardware/qcom/display/libhwcomposer/hwc.cpp'
   'command_line_args' : ['-Wall', '-Wextra', '-Wc++98-compat', '-Wno-long-long', '-Wno-variadic-macros', '-fexceptions', '-fno-rtti', '-fno-strict-aliasing', '-fPIE', '-fpic', '-DNDEBUG', '-DANDROID', '-DUSE_CLANG_COMPLETER', '-std=c++11'\
 , '-x c++', '-I/local/mnt/workspace/naseer/LA.BF64.1/ .', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libgralloc', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/l\
 iboverlay', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libhwcomposer', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libcopybit', '-I/local/mnt/workspace/naseer/\
 LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libqdutils', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libexternal', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/d\
 isplay/libqservice', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libvirtual', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libhdmi', '-isystem/local/mnt/workspac\
 e/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/system/core/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/libhardware/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/lib\
 hardware_legacy/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/ril/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/libnativehelper/include', '-isystem/local/mnt/workspace\
 /naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/arch-arm/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/k\
 ernel/common', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/kernel/arch-arm', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libstdc/include', '-isystem/local/mnt/workspace/nase\
 er/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libstdc/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libm/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libm/include/arm'\
 , '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libthread_db/include/', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/frameworks/native/include', '-isystem/local/mnt/workspace/naseer/LA.BF6\
 4.1/ $ANDROID_BUILD_TOP/frameworks/native/opengl/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/frameworks/av/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/frameworks/base/inclu\
 de', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/out/target/product/$TARGET_PRODUCT/obj/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/out/target/product/$TARGET_PRODUCT/obj/KERNEL_OBJ/\
 usr/include', '-isystem', '/local/mnt/workspace/naseer/installs/ycmd/ycmd/../clang_includes'],
   'unsaved_files' : [('/local/mnt/workspace/naseer/LA.BF64.1/hardware/qcom/display/libhwcomposer/hwc.cpp', '...', 37243)],
   'options' : 143,
 }
 Traceback (most recent call last):
   File "/local/mnt/workspace/naseer/installs/ycmd/third_party/bottle/bottle.py", line 861, in _handle
     return route.call(**args)
   File "/local/mnt/workspace/naseer/installs/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
     rv = callback(*a, **ka)
   File "/local/mnt/workspace/naseer/installs/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
     return callback( *args, **kwargs )
   File "/local/mnt/workspace/naseer/installs/ycmd/ycmd/../ycmd/hmac_plugin.py", line 54, in wrapper
     body = callback( *args, **kwargs )
   File "/local/mnt/workspace/naseer/installs/ycmd/ycmd/../ycmd/handlers.py", line 100, in GetCompletions
     completer.ComputeCandidates( request_data ),
   File "/local/mnt/workspace/naseer/installs/ycmd/ycmd/../ycmd/completers/completer.py", line 158, in ComputeCandidates
     candidates = self._GetCandidatesFromSubclass( request_data )
   File "/local/mnt/workspace/naseer/installs/ycmd/ycmd/../ycmd/completers/completer.py", line 173, in _GetCandidatesFromSubclass
     raw_completions = self.ComputeCandidatesInner( request_data )
   File "/local/mnt/workspace/naseer/installs/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 101, in ComputeCandidatesInner
     raise RuntimeError( NO_COMPLETIONS_MESSAGE )
 RuntimeError: No completions found; errors in the file?
 2015-03-27 15:24:34,267 - INFO - Received event notification
 2015-03-27 15:24:34,268 - DEBUG - Event name: FileReadyToParse
 2015-03-27 15:24:34,268 - INFO - Adding buffer identifiers for file: /local/mnt/workspace/naseer/LA.BF64.1/hardware/qcom/display/libhwcomposer/hwc.cpp
 libclang: crash detected during parsing: {
   'source_filename' : '/local/mnt/workspace/naseer/LA.BF64.1/hardware/qcom/display/libhwcomposer/hwc.cpp'
   'command_line_args' : ['-Wall', '-Wextra', '-Wc++98-compat', '-Wno-long-long', '-Wno-variadic-macros', '-fexceptions', '-fno-rtti', '-fno-strict-aliasing', '-fPIE', '-fpic', '-DNDEBUG', '-DANDROID', '-DUSE_CLANG_COMPLETER', '-std=c++11'\
 , '-x c++', '-I/local/mnt/workspace/naseer/LA.BF64.1/ .', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libgralloc', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/l\
 iboverlay', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libhwcomposer', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libcopybit', '-I/local/mnt/workspace/naseer/\
 LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libqdutils', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libexternal', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/d\
 isplay/libqservice', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libvirtual', '-I/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/qcom/display/libhdmi', '-isystem/local/mnt/workspac\
 e/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/system/core/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/libhardware/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/lib\
 hardware_legacy/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/hardware/ril/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/libnativehelper/include', '-isystem/local/mnt/workspace\
 /naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/arch-arm/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/k\
 ernel/common', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libc/kernel/arch-arm', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libstdc/include', '-isystem/local/mnt/workspace/nase\
 er/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libstdc/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libm/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libm/include/arm'\
 , '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/bionic/libthread_db/include/', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/frameworks/native/include', '-isystem/local/mnt/workspace/naseer/LA.BF6\
 4.1/ $ANDROID_BUILD_TOP/frameworks/native/opengl/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/frameworks/av/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/frameworks/base/inclu\
 de', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/out/target/product/$TARGET_PRODUCT/obj/include', '-isystem/local/mnt/workspace/naseer/LA.BF64.1/ $ANDROID_BUILD_TOP/out/target/product/$TARGET_PRODUCT/obj/KERNEL_OBJ/\
 usr/include', '-isystem', '/local/mnt/workspace/naseer/installs/ycmd/ycmd/../clang_includes'],
   'unsaved_files' : [('/local/mnt/workspace/naseer/LA.BF64.1/hardware/qcom/display/libhwcomposer/hwc.cpp', '...', 37243)],
   'options' : 143,
 }
```

**Comment by naseer** [comment]
vim works fine, although the ycmd in vim was built with the plugin. With emacs, ycmd was built separately from today's master.

**Comment by Valloric** [comment]
Well it says `libclang: crash detected during parsing:` right there in the log, so it's a libclang bug. I recommend filing it upstream with clang. You'll need to produce the file that crashed the compiler though; try to reduce the file to smallest possible repro case.

@r4nt You might be interested.

**Comment by naseer** [comment]
It doesn't crash with vim-ycm with the same file - do you know what's the difference between standalone ycmd and the one that ships with the vim plugin?

**Comment by naseer** [comment]
My vim plugin says - the ycmd version is from Jan 22, let me try updating to a newer version of the vim plugin.


'''
commit ba6e1408fd2f6929a8e3f4dc527ed1096945fef8
Author: Strahinja Val Markovic <val@markovic.io>
Date:   Thu Jan 22 10:14:28 2015 -0800

    Updating to latest ycmd
```

**Comment by naseer** [comment]
Yeah - I updated the vim plugin just now and everything still works fine on vim with the same file.

CC'ing @abingham for info.

**Comment by naseer** [comment]
@Valloric where can I log on the ycmd side the full clang command sent? I want to compare the arguments sent from emacs and vim, to see what's the difference and then file the bug on clang.

**Comment by Valloric** [comment]
> where can I log on the ycmd side the full clang command sent? 

You can't. The server talks to libclang through the C API, not a command-line interface. It does pass flags though; you can see which flags will be passed by calling `:YcmDebugInfo` in Vim when a C/C++ file is the active buffer.

**Comment by naseer** [comment]
Please checkout the difference in https://github.com/abingham/emacs-ycmd/issues/166 - the env variable  in the ycm_extra_conf.py is expanded in vim but not in emacs.
