### ISSUE TITLE
Value for key '&filetype' in FlagsForFile 'client_data' dict is sometimes missing

### ISSUE THREAD

**Issue by ElArtista** [Valloric/ycmd#1106]
My global .ycm_extra_conf.py starts like this:

```
def FlagsForFile(filename, **kwargs):
    # Gather the source filetype
    data = kwargs['client_data']
    logger.info('!Gathering flags!')
    logger.info(filename)
    logger.info(data)
    filetype = data['&filetype']
    ...
```

I've noticed in the logs that sometimes the '&filetype' key in 'client_data' dict in kwargs is sometimes missing as you can see from the bellow log:

```
2018-09-19 21:54:25,919 - INFO - Received ready request
2018-09-19 21:54:25,950 - INFO - Received event notification
2018-09-19 21:54:25,953 - INFO - Received event notification
2018-09-19 21:54:25,953 - INFO - Adding buffer identifiers for file: /home/theartist/Workdir/EnergyCore/demo/src/main.c
2018-09-19 21:54:25,965 - INFO - !Gathering flags!
2018-09-19 21:54:25,965 - INFO - /home/theartist/Workdir/EnergyCore/demo/src/main.c
2018-09-19 21:54:25,965 - INFO - <HashableDict {'&filetype': 'c'}>
2018-09-19 21:54:25,965 - INFO - Gathering include directories for file: /home/theartist/Workdir/EnergyCore/demo/src/main.c
2018-09-19 21:54:25,965 - INFO - Using configuration: /home/theartist/Workdir/EnergyCore/demo/config.mk
2018-09-19 21:54:25,965 - INFO - Using subproject: demo
2018-09-19 21:54:25,987 - INFO - Got include paths for subproject with config "/home/theartist/Workdir/EnergyCore/demo/config.mk": ['demo/include', 'demo/deps/StbImg/include', './include', '/home/theartist/.local/builds/gfxwnd/0.0.1dev/include', '/home/theartist/.local/builds/macu/0.0.2dev/include', '/home/theartist/.local/builds/glad/0.1.16a0/include', '/home/theartist/.local/builds/glfw/3.2.1/include']
2018-09-19 21:54:25,988 - INFO - Using includes: ['demo/include', 'demo/deps/StbImg/include', './include', '/home/theartist/.local/builds/gfxwnd/0.0.1dev/include', '/home/theartist/.local/builds/macu/0.0.2dev/include', '/home/theartist/.local/builds/glad/0.1.16a0/include', '/home/theartist/.local/builds/glfw/3.2.1/include']
2018-09-19 21:54:26,008 - INFO - Got defines for subproject with config "/home/theartist/Workdir/EnergyCore/demo/config.mk": []
2018-09-19 21:54:26,156 - INFO - Received filetype completion available request
2018-09-19 21:54:29,434 - INFO - Received debug info request
2018-09-19 21:54:29,435 - INFO - !Gathering flags!
2018-09-19 21:54:29,435 - INFO - /home/theartist/Workdir/EnergyCore/demo/src/main.c
2018-09-19 21:54:29,436 - INFO - <HashableDict {}>
2018-09-19 21:54:29,436 - ERROR - '&filetype'
Traceback (most recent call last):
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 238, in DebugInfo
    request_data ).DebugInfo( request_data )
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 410, in DebugInfo
    flags, filename = self._FlagsForRequest( request_data ) or []
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 445, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 131, in FlagsForFile
    results = self._GetFlagsFromExtraConfOrDatabase( filename, client_data )
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 181, in _GetFlagsFromExtraConfOrDatabase
    return _CallExtraConfFlagsForFile( module, filename, client_data )
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 300, in _CallExtraConfFlagsForFile
    results = module.FlagsForFile( filename, client_data = client_data )
  File "/home/theartist/.vim/conf/.ycm_extra_conf.py", line 72, in FlagsForFile
    filetype = data['&filetype']
  File "/home/theartist/.dot/dotvim/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/utils.py", line 483, in __getitem__
    return copy.deepcopy( self._dict[ key ] )
KeyError: '&filetype'
```

Should this indicate something or is this a bug?

**Comment by micbou** [comment]
Does it only happen when running the `:YcmToggleLogs`  command?

**Comment by ElArtista** [comment]
Just tested it and yep, you are right!

**Comment by micbou** [comment]
Thanks for the confirmation. This should be fixed by PR https://github.com/Valloric/YouCompleteMe/pull/3148.
