### ISSUE TITLE
UnicodeEncodeError when try to 'GoToDefinition' in C# file which  is cp936 encoding

### ISSUE THREAD

**Issue by fftyjw** [Valloric/ycmd#1127]
set fileencoding? is cp936

`Traceback (most recent call last):
  File "/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 107, in wrapper
    return callback( *args, **kwargs )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 85, in RunCompleterCommand
    request_data ) )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 340, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 150, in <lambda>
    fallback_to_declaration = True ) ),
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 179, in _SolutionSubcommand
    return getattr( solutioncompleter, method )( **kwargs )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 473, in _GoToImplementation
    return self._GoToDefinition( request_data )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 445, in _GoToDefinition
    definition[ 'Column' ] ) )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 672, in _BuildLocation
    contents = GetFileLines( request_data, filename )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer_utils.py", line 240, in GetFileLines
    return SplitLines( GetFileContents( request_data, filename ) )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer_utils.py", line 229, in GetFileContents
    return ToUnicode( ReadFile( filename ) )
  File "/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/utils.py", line 77, in ReadFile
    return f.read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 7476: invalid start byte
`

**Comment by bstaletic** [comment]
ycmd assumes it is working with utf8 encoded files. Not because we were lazy, but because many tools that we depend on make the same assumption. Also, there's no (easy?) way to detect encoding.
