### ISSUE TITLE
Clangd binary at None is out-of-date please update

### ISSUE THREAD

**Issue by JackDrogon** [Valloric/ycmd#1185]
I updated my ycm to `c25e449f`. After that, my vim was often killed by segentfault. I found that vim crash at `PollFileParseResponse` which is a ycm scirpt function. I opened ycmd error log, found that:
```
2019-01-29 15:43:47,076 - INFO - Received ready request
2019-01-29 15:43:47,272 - INFO - Received event notification
2019-01-29 15:43:47,288 - ERROR - Semantic completion not available for ['cpp']
Traceback (most recent call last):
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/server_state.py", line 98, in FiletypeCompletionAvailable
    self.GetFiletypeCompleter( filetypes )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/server_state.py", line 80, in GetFiletypeCompleter
    for filetype in current_filetypes ]
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/server_state.py", line 80, in <listcomp>
    for filetype in current_filetypes ]
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/server_state.py", line 64, in _GetFiletypeCompleterForFiletype
    completer = module.GetCompleter( self._user_options )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/hook.py", line 32, in GetCompleter
    if ShouldEnableClangdCompleter( user_options ):
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/clangd_completer.py", line 160, in ShouldEnableClangdCompleter
    third_party_clangd = Get3rdPartyClangd()
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/clangd_completer.py", line 106, in Get3rdPartyClangd
    raise RuntimeError( error )
RuntimeError: clangd binary at None is out-of-date please update.

....
....


2019-01-29 15:46:10,259 - INFO - Adding buffer identifiers for file: xxx.cc
Traceback (most recent call last):
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/handlers.py", line 67, in EventNotification
    event_handler )( request_data )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/clang_completer.py", line 384, in OnFileReadyToParse
    with self._files_being_compiled.GetExclusive( filename ):
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/ephemeral_values_set.py", line 62, in __enter__
    raise RuntimeError( ALREADY_PARSING_MESSAGE )
RuntimeError: File already being parsed.
2019-01-29 15:46:10,279 - INFO - Received event notification
2019-01-29 15:46:10,280 - INFO - Adding buffer identifiers for file: xxx.cc
Traceback (most recent call last):
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/handlers.py", line 67, in EventNotification
    event_handler )( request_data )
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/clang_completer.py", line 384, in OnFileReadyToParse
    with self._files_being_compiled.GetExclusive( filename ):
  File "/Users/Nepenthe/.vim/bundle/YouCompleteMe.vim/third_party/ycmd/ycmd/completers/cpp/ephemeral_values_set.py", line 62, in __enter__
    raise RuntimeError( ALREADY_PARSING_MESSAGE )
RuntimeError: File already being parsed.
```

I try to disable clangd completer. But i didn't find it. Is there some params to control that?

**Comment by bstaletic** [comment]
That error is not preventing ycmd to work, but

> `RuntimeError: File already being parsed.`

That is coming from the libclang completer and means that ycmd is still busy parsing your translation unit. It will work once ycmd is done.

**Comment by JackDrogon** [comment]
1. I want to disable clangd completer.
2. From vimlog, this is the lastlog maybe it trigger other problem which case segmentfault.

**Comment by bstaletic** [comment]
> I want to disable clangd completer.

Clangd is not enabled. You can check in `:YcmDebugInfo`. It's still considered experimental and so ycmd still defaults to the older libclang based completer.

> From vimlog, this is the lastlog maybe it trigger other problem which case segmentfault.

What segfault? You didn't show that.

**Comment by JackDrogon** [comment]
en, my statement is a bit less accurate. I want to disable the error log of `Clangd binary at None is out-of-date please update.`

> I foud that vim crash at PollFileParseResponse which is a ycm scirpt function. 

log: call function <SNR>225_PollFileParseResponse[9]..<SNR>225_Pyeval('ycm_state.ShouldResendFileParseRequest()')

**Comment by bstaletic** [comment]
> e, my statement is a bit less accurate. I just want to disable the error log of `Clangd binary at None is out-of-date please update`.

You can't and there's no reason to do that as that error is harmless.

> I found that vim crash at PollFileParseResponse which is a ycm scirpt function.

That's why I told you to put `let g:ycm_log_level='debug'` in your vimrc and post the whole logs. `:messages` and `:YcmDebugInfo` could be useful too.

**Comment by puremourning** [comment]
Please see CONTRIBUTING.md

**Comment by puremourning** [comment]
> I updated my ycm 

Actually, you reported this issue on the wrong repo! Please could you report whatever issue you are actually seeing on the YCM repo and complete the issue template ?

Thanks.
