### ISSUE TITLE
hmac_secret error

### ISSUE THREAD

**Issue by henry-y** [Valloric/ycmd#154]
After running "nohup python ~/.emacs.d/ycmd/ycmd/", I got the following error in nohup.out:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.emacs.d/3rd/ycmd/ycmd/__main__.py", line 164, in <module>
    Main()
  File "/root/.emacs.d/3rd/ycmd/ycmd/__main__.py", line 139, in Main
    options, hmac_secret = SetupOptions( args.options_file )
  File "/root/.emacs.d/3rd/ycmd/ycmd/__main__.py", line 119, in SetupOptions
    hmac_secret = base64.b64decode( options[ 'hmac_secret' ] )
KeyError: 'hmac_secret'
```

Could you please check it? I've used ycmd for quite a while now and haven't updated it for some time, I got this error after updating it.

**Comment by Kuxe** [comment]
I have this issue too on Arch Linux, similar (nearly identical) logs:

```
[kuxe@kuxe ~]$ python2.7 ~/programming/gitrepos/ycmd/ycmd/
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kuxe/programming/gitrepos/ycmd/ycmd/__main__.py", line 169, in <module>
    Main()
  File "/home/kuxe/programming/gitrepos/ycmd/ycmd/__main__.py", line 139, in Main
    options, hmac_secret = SetupOptions( args.options_file )
  File "/home/kuxe/programming/gitrepos/ycmd/ycmd/__main__.py", line 119, in SetupOptions
    hmac_secret = base64.b64decode( options[ 'hmac_secret' ] )
KeyError: 'hmac_secret'
[kuxe@kuxe ~]$ 
```

In /ycmd/ycmd/default_settings.json I have tried with and without a value for "hmac_secret", same error in both cases

**Comment by Valloric** [comment]
I'm not sure what you're trying to do, but [look at how the example client starts ycmd](https://github.com/Valloric/ycmd/blob/master/examples/example_client.py). The key `hmac_secret` needs to be added by the caller to facilitate HMAC authorization (see ycmd readme for details on that).
