### ISSUE TITLE
Error with non-ascii character in file name

### ISSUE THREAD

**Issue by ptrv** [Valloric/ycmd#177]
I have a file with non-ascii cahracter I want to run completion on and I get the following error:

The issue appeared because we did some test for `emacs-ycmd` regarding encoding. We had some problems with current Emacs HEAD.

```
2015-07-16 23:51:40,136 - INFO - Adding buffer identifiers for file: /home/peter/src/test/testå.cpp
2015-07-16 23:51:44,529 - INFO - Received completion request
2015-07-16 23:51:44,530 - DEBUG - Using filetype completion: False
Traceback (most recent call last):
  File "/home/peter/src/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/peter/src/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/peter/src/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/home/peter/src/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/home/peter/src/ycmd/ycmd/../ycmd/handlers.py", line 101, in GetCompletions
    completer.ComputeCandidates( request_data ),
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/general/general_completer_store.py", line 83, in ComputeCandidates
    candidates += completer.ComputeCandidates( request_data )
  File "/home/peter/src/ycmd/ycmd/../ycmd/completers/all/identifier_completer.py", line 52, in ComputeCandidates
    ToUtf8IfNeeded( request_data[ 'filetypes' ][ 0 ] ) )
IndexError: bitset::set: __position (which is 18446744073709551555) >= _Nb (which is 128)
```

**Comment by Valloric** [comment]
I think this is issue #53. Is it? That or #109.

**Comment by ptrv** [comment]
I think the mentioned issues are both related to this one but #53 is closer.

I think it's a general problem and not only with filename completion like in #53.
Should I close this one, though?

**Comment by Valloric** [comment]
Let's leave this around for a bit; please provide a test-case though. The more we have it, the easier to track this down in all the necessary places (I'm pretty sure it's going to involve changing _many_ things).

**Comment by ptrv** [comment]
Here is an example file which brings up the error:
https://gist.github.com/ptrv/c205d73c7edd316b523f

**Comment by oblitum** [comment]
Got same error from general filetype ([journal](https://github.com/junegunn/vim-journal)). Not regarding the filename but non-ascii content.

**Comment by oblitum** [comment]
Well, I just ended up here googling, but have already gone through it before: https://github.com/Valloric/YouCompleteMe/issues/1378#issuecomment-121460358.
