### ISSUE TITLE
Exception when triggering dot-completion in Python

### ISSUE THREAD

**Issue by thirtythreeforty** [Valloric/ycmd#182]
Hello, I can get ycmd to crash when using YouCompleteMe by attempting to trigger dot-completion on the following file:

```
#!/bin/env python3

import sys
sys.
```
At the `.`, pressing `<C-Space>` causes the following backtrace in the ycmd log:
```
2015-07-23 15:42:17,996 - INFO - Received completion request
Traceback (most recent call last):
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 101, in GetCompletions
    completer.ComputeCandidates( request_data ),
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 163, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 179, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 83, in ComputeCandidatesInner
    for completion in script.completions() ]
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/parser/fast.py", line 78, in __getitem__
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
  File "/home/ghilliard/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi/jedi/parser/fast.py", line 78, in <genexpr>
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
AttributeError: 'MergedNamesDict' object has no attribute 'get'
```

As to be expected from a Jedi crash, this is Python specific.  C++ and C work fine.

I'm running bfcfa21fb87789e88c803ac1f2b1ab766961f0b4, which is the version depended upon by YouCompleteMe as of this writing.

Is this a Jedi problem, or is it caused by YouCompleteMe?

**Comment by thirtythreeforty** [comment]
Whoops, just found this on the [Jedi bugtracker](https://github.com/davidhalter/jedi/issues/589).  Sorry for bugging you!  YCM works great :smiley:
