### ISSUE TITLE
LookupError: unknown encoding on Mac with Python 2

### ISSUE THREAD

**Issue by ptrv** [Valloric/ycmd#395]
With latest `ycmd` I get the following error on Mac with Py2:

```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/peter/src/ycmd/ycmd/__main__.py", line 181, in <module>
    Main()
  File "/Users/peter/src/ycmd/ycmd/__main__.py", line 151, in Main
    options, hmac_secret = SetupOptions( args.options_file )
  File "/Users/peter/src/ycmd/ycmd/__main__.py", line 127, in SetupOptions
    options = user_options_store.DefaultOptions()
  File "/Users/peter/src/ycmd/ycmd/../ycmd/user_options_store.py", line 52, in DefaultOptions
    with open( settings_path ) as f:
LookupError: unknown encoding: 

Process ycmd-server exited abnormally with code 1
```

I have a python 2 installation from homebrew

**Comment by micbou** [comment]
Could you check if PR #397 fix your issue?

**Comment by Valloric** [comment]
Thanks for the report!

**Comment by ptrv** [comment]
Thanks for the fix. I confirm, the issue is gone.
