### ISSUE TITLE
ycmd crashes after update

### ISSUE THREAD

**Issue by m-novikov** [Valloric/ycmd#411]
After last update ycmd crashes with following traceback.
Reason is python2 open has no encoding keyword argument.
I suggest use io.open in PY2/PY3
```python
Traceback (most recent call last):                                                                                                                     
  File "<string>", line 19, in <module>                                                                                                                
  File "/home/nes/config-files/.vim/bundle/YouCompleteMe/autoload/../python/ycm/setup.py", line 38, in SetUpYCM                                        
    base.LoadJsonDefaultsIntoVim()                                                                                                                     
  File "/home/nes/config-files/.vim/bundle/YouCompleteMe/autoload/../python/ycm/base.py", line 46, in LoadJsonDefaultsIntoVim                          
    defaults = user_options_store.DefaultOptions()                                                                                                     
  File "/home/nes/config-files/.vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/user_options_store.py", line 55, in DefaultOptions     
    options = json.loads( ReadFile( settings_path ) )                                                                                                  
  File "/home/nes/config-files/.vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/utils.py", line 55, in ReadFile                        
    with open( filepath, encoding = 'utf8' ) as f:                                                                                                     
TypeError: 'encoding' is an invalid keyword argument for this function    
```

**Comment by m-novikov** [comment]
Problem was in builtins.py module found in PYTHONPATH.
