### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:59454/completions

### ISSUE THREAD

**Issue by Yevgnen** [Valloric/ycmd#432]
I built ycmd with python3 and use it for python3 completion in emacs. But I got some thing like the following in the *ycmd-server* buffer. It seems that the ycmd server is listening on 59482 while the 401 is happening from 59485. [https://github.com/abingham/emacs-ycmd/issues/275](https://github.com/abingham/emacs-ycmd/issues/275)

    2016-03-15 20:37:27,888 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
    serving on http://127.0.0.1:59482
    2016-03-15 20:37:27,927 - INFO - Received event notification
    2016-03-15 20:37:27,927 - DEBUG - Event name: FileReadyToParse
    2016-03-15 20:37:27,927 - INFO - Adding buffer identifiers for file: /Users/user/test.py
    2016-03-15 20:37:27,928 - INFO - Received event notification
    2016-03-15 20:37:27,928 - DEBUG - Event name: FileReadyToParse
    2016-03-15 20:37:27,928 - INFO - Adding buffer identifiers for file: /Users/user/test.py
    2016-03-15 20:37:27,970 - INFO - Starting JediHTTP server
    2016-03-15 20:37:27,970 - INFO - using port 59485
    2016-03-15 20:37:52,989 - INFO - Received completion request
    2016-03-15 20:37:52,989 - DEBUG - Using filetype completion: True
    2016-03-15 20:37:52,990 - DEBUG - Making JediHTTP request: POST b'http://127.0.0.1:59485/completions' {'content-type': 'application/json', 'x-jedihttp-hmac': b'5iZ+jHZNOKI6NSvWwhCpyQpW/2agtPh9qrpfY68ipuU='} b'{"source": "#!/usr/bin/env python3\\n# -*- coding: utf-8 -*-\\n\\nimport numpy as np\\nfrom scipy import linalg as spla\\n\\n\\nnp.z\\n", "col": 4, "source_path": "/Users/user/test.py", "line": 8}'
    2016-03-15 20:37:52,998 - INFO - Starting new HTTP connection (1): 127.0.0.1
    2016-03-15 20:37:53,004 - DEBUG - "POST /completions HTTP/1.1" 401 746
    Traceback (most recent call last):
      File "/usr/local/ycmd/third_party/bottle/bottle.py", line 861, in _handle
        return route.call(**args)
      File "/usr/local/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
        rv = callback(*a, **ka)
      File "/usr/local/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
        return callback( *args, **kwargs )
      File "/usr/local/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
        body = callback( *args, **kwargs )
      File "/usr/local/ycmd/ycmd/../ycmd/handlers.py", line 112, in GetCompletions
        .ComputeCandidates( request_data ) )
      File "/usr/local/ycmd/ycmd/../ycmd/completers/completer.py", line 169, in ComputeCandidates
        candidates = self._GetCandidatesFromSubclass( request_data )
      File "/usr/local/ycmd/ycmd/../ycmd/completers/completer.py", line 185, in _GetCandidatesFromSubclass
        raw_completions = self.ComputeCandidatesInner( request_data )
      File "/usr/local/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 255, in ComputeCandidatesInner
        for completion in self._JediCompletions( request_data ) ]
      File "/usr/local/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 260, in _JediCompletions
        request_data )[ 'completions' ]
      File "/usr/local/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 199, in _GetResponse
        response.raise_for_status()
      File "/usr/local/ycmd/third_party/requests/requests/models.py", line 840, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:59485/completions
    2016-03-15 20:37:54,658 - INFO - Received completion request
    2016-03-15 20:37:54,658 - DEBUG - Using filetype completion: True
    2016-03-15 20:37:54,659 - DEBUG - Making JediHTTP request: POST b'http://127.0.0.1:59485/completions' {'content-type': 'application/json', 'x-jedihttp-hmac': b'vljH4z07pRhMjRY7qp8Thbw2gbV7eUtx2phHax0q5HE='} b'{"source": "#!/usr/bin/env python3\\n# -*- coding: utf-8 -*-\\n\\nimport numpy as np\\nfrom scipy import linalg as spla\\n\\n\\nnp.ze\\n", "col": 5, "source_path": "/Users/user/test.py", "line": 8}'
    2016-03-15 20:37:54,660 - INFO - Starting new HTTP connection (1): 127.0.0.1
    2016-03-15 20:37:54,663 - DEBUG - "POST /completions HTTP/1.1" 401 746
    Traceback (most recent call last):
      File "/usr/local/ycmd/third_party/bottle/bottle.py", line 861, in _handle
        return route.call(**args)
      File "/usr/local/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
        rv = callback(*a, **ka)
      File "/usr/local/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
        return callback( *args, **kwargs )
      File "/usr/local/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
        body = callback( *args, **kwargs )
      File "/usr/local/ycmd/ycmd/../ycmd/handlers.py", line 112, in GetCompletions
        .ComputeCandidates( request_data ) )
      File "/usr/local/ycmd/ycmd/../ycmd/completers/completer.py", line 169, in ComputeCandidates
        candidates = self._GetCandidatesFromSubclass( request_data )
      File "/usr/local/ycmd/ycmd/../ycmd/completers/completer.py", line 185, in _GetCandidatesFromSubclass
        raw_completions = self.ComputeCandidatesInner( request_data )
      File "/usr/local/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 255, in ComputeCandidatesInner
        for completion in self._JediCompletions( request_data ) ]
      File "/usr/local/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 260, in _JediCompletions
        request_data )[ 'completions' ]
      File "/usr/local/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 199, in _GetResponse
        response.raise_for_status()
      File "/usr/local/ycmd/third_party/requests/requests/models.py", line 840, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:59485/completions
    2016-03-15 20:37:57,910 - INFO - Received health request
    
So, is this a ycmd issue ? Any help will be appreciated! Thank you!

**Comment by Valloric** [comment]
@vheon This looks weird; we're getting this unauthorized error when talking to JediHTTP.

**Comment by vheon** [comment]
Yes, is weird :confused: I will take a look as soon as possible

**Comment by vheon** [comment]
@Yevgnen how did you install `ycmd`? on what os are you? which version of python?

**Comment by Yevgnen** [comment]
Thanks for your reply ! I built it with Python 3.5 install by homebrew without any error on OSX.

**Comment by micbou** [comment]
@Yevgnen Could you try again with the latest version of ycmd?

**Comment by Yevgnen** [comment]
@micbou Ok, I'll try it as soon as possible.

**Comment by Yevgnen** [comment]
I guess this issue is gone under a python 3.5.2 build, even though I got other things like 

```
Traceback (most recent call last):
  File "/usr/local/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/usr/local/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "/usr/local/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/usr/local/ycmd/ycmd/../ycmd/handlers.py", line 100, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/usr/local/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/usr/local/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/usr/local/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 113, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?
```
which seems to relate to existed issue.

**Comment by micbou** [comment]
This is different. Initial issue was a connection problem with [the JediHTTP server](https://github.com/vheon/JediHTTP) (which is used to provide Python completions) while this one is a C/C++ completion issue. Are completions working in Python files?

**Comment by Yevgnen** [comment]
I know that's different issue, happens in a c++ file when typing things like `#include <iosream>. I confirm that the origin issue in Python completion is gone.
