### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by asdyjd** [Valloric/ycmd#445]
I have compiled ycmd.
But there is an error when running.

asdyjd@yujinding:~/.emacs.d/ycmd$ python ycmd --options_file /home/asdyjd/.emacs.d/ycmd/cpp/ycm/.ycm_extra_conf.py
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in run_module_as_main
"__main_", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in run_code
exec code in run_globals
File "/home/asdyjd/.emacs.d/ycmd/ycmd/__main_.py", line 183, in
Main()
File "/home/asdyjd/.emacs.d/ycmd/ycmd/main.py", line 153, in Main
options, hmac_secret = SetupOptions( args.options_file )
File "/home/asdyjd/.emacs.d/ycmd/ycmd/main.py", line 130, in SetupOptions
user_options = json.loads( ReadFile( options_file ) )
File "/usr/lib/python2.7/json/init.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by micbou** [comment]
See my comment in abingham/emacs-ycmd#290.
