### ISSUE TITLE
Encoding error in cs_completer on Mac 

### ISSUE THREAD

**Issue by notrev** [Valloric/ycmd#447]
I believe this issue is similar to #395 and #419.

I am using Vundle to manage VIM plugins and I have just updated them (with :VundleUpdate).
After the update, the C# autocomplete stopped working.
It seems it is not starting OmniSharp server.

Error Log content:

```
2016-04-01 15:43:50,290 - INFO - Received event notification
2016-04-01 15:43:50,323 - INFO - Received event notification
2016-04-01 15:43:50,324 - INFO - Adding buffer identifiers for file: /Users/everton/Project/vr/vr-gallery/VRGallery/Assets/Scripts/Controllers/ImagePlayerController.cs
2016-04-01 15:43:50,327 - INFO - Selected solution file /Users/everton/Project/vr/vr-gallery/VRGallery/VRGallery.sln as it is the first one found
2016-04-01 15:43:50,327 - INFO - Starting OmniSharp server
2016-04-01 15:43:50,327 - INFO - Loading solution file /Users/everton/Project/vr/vr-gallery/VRGallery/VRGallery.sln
2016-04-01 15:43:50,331 - INFO - using port 50004
Traceback (most recent call last):
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
    return callback( *args, **kwargs )
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 79, in EventNotification
    event_handler )( request_data )
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 225, in OnFileReadyToParse
    solutioncompleter._StartServer()
  File "/Users/everton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cs/cs_completer.py", line 382, in _StartServer
    with open( self._filename_stderr, 'w' ) as fstderr:
LookupError: unknown encoding: 
2016-04-01 15:43:51,443 - INFO - Received health request
2016-04-01 15:43:51,448 - INFO - Received filetype completion available request
2016-04-01 15:53:49,742 - INFO - Received health request
2016-04-01 15:54:30,070 - INFO - Received debug info request
```

**Comment by notrev** [comment]
I found out that **YouCompleteMe** was using an old revision of **ycmd**.
I changed to **ycmd**'s master branch, pulled the latest modifications with **git pull** and recompiled **YouCompleteMe**. After this, it started working again.
