### ISSUE TITLE
Ycmd build system assumes that the current python on OSX is the same to compile ycmd for.

### ISSUE THREAD

**Issue by Mistobaan** [Valloric/ycmd#479]
I tried to install ycmd on macosx and it took me a while to actually figure out that:
1) you need python3 (both for Sublime Text3 and for the example)

2) the build system tries to build the library from the output of python-config --prefix. So even if I was running `python3 build.py` it would still try to use the default python configuration (that is 2.7 on my machine).

it would be useful if the build.py uses the current python executable to determine the prefix.

**Comment by Mistobaan** [comment]
and yet still not able to run it 
```
Trying to start server...
(b'', b'Fatal Python error: PyThreadState_Get: no current thread\n')
Traceback (most recent call last):
  File "example_client.py", line 494, in <module>
    Main()
  File "example_client.py", line 474, in Main
    server.WaitUntilReady()
  File "example_client.py", line 200, in WaitUntilReady
    print(self._popen_handle.communicate())
  File "/Users/fmilo/anaconda/envs/py3k/lib/python3.5/subprocess.py", line 1068, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Users/fmilo/anaconda/envs/py3k/lib/python3.5/subprocess.py", line 1693, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/Users/fmilo/anaconda/envs/py3k/lib/python3.5/selectors.py", line 342, in register
    key = super().register(fileobj, events, data)
  File "/Users/fmilo/anaconda/envs/py3k/lib/python3.5/selectors.py", line 228, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/Users/fmilo/anaconda/envs/py3k/lib/python3.5/selectors.py", line 215, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/Users/fmilo/anaconda/envs/py3k/lib/python3.5/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=4>
```

**Comment by puremourning** [comment]
Your Python must be built with --enable-shared.

**Comment by Valloric** [comment]
@puremourning can we detect this problem somehow in build.py and report an error message?

**Comment by puremourning** [comment]
I thought we did :/
