### ISSUE TITLE
Compilation fails on debian stretch

### ISSUE THREAD

**Issue by victorklos** [Valloric/ycmd#494]
When running `build.py` the python libraries cannot be found (this is invoked from YouCompleteMe):

```
Traceback (most recent call last):
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 507, in <module>
    Main()
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 494, in Main
    BuildYcmdLib( args )
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 380, in BuildYcmdLib
    full_cmake_args.extend( CustomPythonCmakeArgs() )
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 253, in CustomPythonCmakeArgs
    python_library, python_include = FindPythonLibraries()
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 235, in FindPythonLibraries
    return FindPythonLibrariesOnLinux()
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 170, in FindPythonLibrariesOnLinux
    ldconfig_output = CheckOutput( [ 'ldconfig', '-p' ] ).strip().decode( 'utf8' )
  File "/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 126, in CheckOutput
    process = subprocess.Popen( stdout=subprocess.PIPE, *popen_args, **kwargs )
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./install.py", line 32, in <module>
    Main()
  File "./install.py", line 21, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/victor/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py']' returned non-zero exit status 1
```

The `ldconfig` call fails because it is not in the path but located in `/sbin`. Changing `build.py` line 120 from

    ldconfig_output = CheckOutput( [ 'ldconfig', '-p' ] ).strip().decode( 'utf8' )

to

    ldconfig_output = CheckOutput( [ '/sbin/ldconfig', '-p' ] ).strip().decode( 'utf8' )

fixes it temporarily. A thorough fix should first try to locate the `ldconfig` executable.

**Comment by NotAFile** [comment]
This happens for me too.

Thank you for the temporary fix.

**Comment by vheon** [comment]
I guess we could add `/sbin/` to the `env` when we call `CheckOutput` in `FindPythonLibrariesOnLinux`.

**Comment by Valloric** [comment]
This is the second report we have of this, so it doesn't seem to be caused by individual system configuration. In other words, we need to fix this.

**Comment by vheon** [comment]
I'll look into this :)

**Comment by micbou** [comment]
@vheon Don't bother, I am already working on it.

**Comment by vheon** [comment]
@micbou ops I read the comment too late :(

**Comment by vheon** [comment]
@micbou I saw your commit in your branch and I see that you're restructuring the whole finding process so I'll wait for your PR 👍
