### ISSUE TITLE
RustCompleter error

### ISSUE THREAD

**Issue by deckardbsd** [Valloric/ycmd#497]
I've installed YouCompleteMe using: `./install.py --system-boost --clang-completer --racer-completer --tern-completer`.

I have installed rust from fedora 23 repo, 
`rustc --version`

> rustc  1.8.0 (db2939409 `2016-04-11)

When I try to use autocomplete in vim, racerd crashes as soon as I type: `use std::`

`YcmDebugInfo`

> 
Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.8.0 (tags/RELEASE_380/final)
-- Server running at: http://127.0.0.1:36207
-- Server process ID: 1384
-- Server logfiles:
--   /tmp/ycm_temp/server_36207_stdout.log
--   /tmp/ycm_temp/server_36207_stderr.log

`cat /tmp/ycm_temp/server_36207_stderr.log`

```
2016-05-17 22:26:05,259 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-05-17 22:26:05,377 - INFO - Received completion request
2016-05-17 22:26:05,378 - INFO - RustCompleter._GetResponse
2016-05-17 22:26:05,380 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-05-17 22:26:05,450 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2016-05-17 22:26:05,452 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2016-05-17 22:26:05,456 - INFO - Received completion request
2016-05-17 22:26:05,457 - INFO - RustCompleter._GetResponse
2016-05-17 22:26:05,459 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-05-17 22:26:05,461 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=46850): Max retries exceeded with url: /list_completions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fee64551590>: Failed to establish a new connection: [Errno 111] Connection refused',))

2016-05-17 22:26:05,466 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2016-05-17 22:26:05,469 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2016-05-17 22:26:05,519 - INFO - Received completion request
2016-05-17 22:26:05,520 - INFO - RustCompleter._GetResponse
2016-05-17 22:26:05,523 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-05-17 22:26:05,525 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=46850): Max retries exceeded with url: /list_completions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fee645d6d90>: Failed to establish a new connection: [Errno 111] Connection refused',))
2016-05-17 22:26:05,627 - INFO - Received completion request
2016-05-17 22:26:05,628 - INFO - RustCompleter._GetResponse
2016-05-17 22:26:05,631 - INFO - Starting new HTTP connection (1): 127.0.0.1
2016-05-17 22:26:05,636 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/handlers.py", line 98, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 239, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 257, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 171, in _GetResponse
    headers = extra_headers )
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/bsabin/dotfiles/.vim/bundle/dein/.dein/third_party/ycmd/third_party/requests/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=46850): Max retries exceeded with url: /list_completions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fee645d6f90>: Failed to establish a new connection: [Errno 111] Connection refused',))
2016-05-17 22:26:06,578 - INFO - Received event notification
2016-05-17 22:26:06,579 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
2016-05-17 22:26:06,585 - INFO - Received event notification
2016-05-17 22:26:06,586 - INFO - Adding ONE buffer identifier for file: /home/bsabin/Playground/rust_tut/first.rs
2016-05-17 22:26:07,312 - INFO - Received event notification
2016-05-17 22:26:07,312 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
2016-05-17 22:26:15,192 - INFO - Received event notification
2016-05-17 22:26:15,196 - INFO - Received event notification
2016-05-17 22:26:15,197 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
```

`cat /tmp/ycm_temp/racerd_46850_stderr.log`

`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', ../src/libcore/result.rs:746                                                                                                           
stack backtrace:                                                                
   1:     0x5586cdda8300 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
`

**Comment by Valloric** [comment]
@jwilm Thoughts?

**Comment by jwilm** [comment]
@deckardbsd  thanks for the logs!

I think `NotPresent` comes from `::std::env::var` which racer uses to read `RUST_SRC_PATH`. @deckardbsd what happens if you set that or the corresponding vimrc variable?

**Comment by deckardbsd** [comment]
Same thing.

**Comment by deckardbsd** [comment]
After I set the g:ycm_rust_src_path="/usr..../src/" the /tmp/ycmp_temp/racerd_aabb_stderr.log is empty, but racerd still crashes.

**Comment by jwilm** [comment]
@deckardbsd anything in the racerd stdout log?

**Comment by deckardbsd** [comment]
Right now I got:
`1 thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', ../src/libcore/result.rs:746                                                                                                       
  2 stack backtrace:                                                                
  3    1:     0x5628fe4d3300 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv`

in racerd_xxyy_stderr.log


And in racerd_aabb_stdout.log
`racerd listening at 127.0.0.1:39542`

**Comment by jwilm** [comment]
Running _racerd_ manually looks like this:

```
Joes-MBP ➜  ~/code/racerd  target/release/racerd serve
racerd listening at 127.0.0.1:3048
```

So far, so good. Note that I **did not** set the `RUST_SRC_PATH` environment variable which racer requires. Now, I'm going to hit it with this post query:

```
curl -H "Content-Type: application/json" -d '{"buffers":[{"file_path":"src.rs","contents":"use std::path::Path;\nfn main() {\nlet p = &Path::new(\"test\")\n}\n"}],"file_path":"src.rs","line":3,"column":16}' 127.0.0.1:3048/find_definition
```

Basically, it's telling racerd there's a file "src.rs" and giving it the contents. It's asking for a completion from the standard library. When I run that request, racerd output looks like this:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

which seems to match what you're seeing. Now, if I restart racerd with that environment variable set and run the query again, nothing shows up in the racerd log (it was successful), and the response looks like this:

```json
{"file_path":"/Users/jwilm/rust/rustc-src/1.6.0/src/libstd/path.rs","column":11,"line":1357,"text":"new","context":"pub fn new<S: AsRef<OsStr> + ?Sized>(s: &S) -> &Path {","kind":"Function"}
```

I've looked through the racer and racerd source code, and there's nothing else accessing environment variables at run time. I must insist that `RUST_SRC_PATH` is not set when your racerd starts up. It's the only thing that I can think of which would cause the exhibited behavior. You can make sure it's set in one of two ways:

-  Run this snippet with your rust source path _and then_ start vim in the same terminal session
```bash
export RUST_SRC_PATH="/path/to/rustc-whatever/src"
```
- Update your _.vimrc_ to include
```viml
let g:ycm_rust_src_path = '/path/to/rustc-whatever/src'
```

**Comment by deckardbsd** [comment]
Oh, yes. I am setting the variable after I start vim and then I restart YCM. I will set it in vimrc and try again.

**Comment by deckardbsd** [comment]
Ok, no crash, but I get no list populated in vim. 
`169 2016-05-18 22:19:35,452 - INFO - Received event notification                    
170 2016-05-18 22:19:35,453 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
171 2016-05-18 22:19:35,594 - INFO - Received event notification                    
172 2016-05-18 22:19:35,595 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
173 2016-05-18 22:19:35,977 - INFO - Received event notification                    
174 2016-05-18 22:19:35,977 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
175 2016-05-18 22:19:36,325 - INFO - Received event notification                    
176 2016-05-18 22:19:36,325 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs
177 2016-05-18 22:19:36,626 - INFO - Received event notification                    
178 2016-05-18 22:19:36,627 - INFO - Adding buffer identifiers for file: /home/bsabin/Playground/rust_tut/first.rs`

**Comment by deckardbsd** [comment]
Splendid, it works ! Sorry for bothering you.
I didn't know that if I set g:ycm_rust_src_path after I start vim & then restart YCM will cause this crash.

Should I close the issue ?

Thanks !
