### ISSUE TITLE
ycmd not impl shutdown?

### ISSUE THREAD

**Issue by pass86** [Valloric/ycmd#558]
Executing VimLeave Auto commands for "*"
autocommand call s:OnVimLeave()

Error detected while processing function <SNR>51_OnVimLeave:
line    1:   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xyz/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 337, in OnVimLeave
    self._ShutdownServer()
  File "/Users/xyz/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 214, in _ShutdownServer
    SendShutdownRequest()
  File "/Users/xyz/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/shutdown_request.py", line 54, in SendShutdownRequest
    request.Start()
  File "/Users/xyz.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/shutdown_request.py", line 42, in Start
    TIMEOUT_SECONDS )
  File "/Users/xyz/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 81, in PostDataToHandler
    timeout ) )
  File "/Users/xyz/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 180, in JsonFromFuture
    response.raise_for_status()
  File "/Users/xyz/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/requests/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:62141/shutdown
Executing VimLeave Auto commands for "*"

**Comment by vheon** [comment]
What you're reporting is actually a YCM problem and not a ycmd bug. You probably have to run `git submodule update --init --recursive` in the YouCompleteMe directory. I'm pretty confident that this is the issue so I'm closing. If you find otherwise we can always re-open it :+1:

**Comment by pass86** [comment]
Fixed, thank you.

**Comment by pass86** [comment]
Sometimes shutdown do not finish.Python process and mono-sgen32 process is still is Activity Monitor.

Finish log
xyz-MC1:ycm_temp xyz$ tail server_60745_stderr.log
2016-07-28 16:55:42,261 - INFO - Received event notification
2016-07-28 16:55:42,266 - INFO - Received event notification
2016-07-28 16:55:42,268 - INFO - Received event notification
2016-07-28 16:55:42,270 - INFO - Received event notification
2016-07-28 16:55:42,272 - INFO - Received event notification
2016-07-28 16:55:42,274 - INFO - Received shutdown request
2016-07-28 16:55:42,379 - INFO - Stopping OmniSharp server
2016-07-28 16:55:42,379 - INFO - Starting new HTTP connection (1): localhost
2016-07-28 16:55:43,447 - INFO - Starting new HTTP connection (1): localhost
2016-07-28 16:55:43,656 - INFO - Stopped OmniSharp server

Not finish log:
xyz-MC1:ycm_temp xyz$ tail server_65106_stderr.log
2016-07-28 16:42:49,220 - INFO - Received event notification
2016-07-28 16:42:49,220 - INFO - using port 65125
2016-07-28 16:42:49,222 - INFO - Received event notification
2016-07-28 16:42:49,222 - INFO - Received event notification
2016-07-28 16:42:49,223 - INFO - Adding buffer identifiers for file: /Users/xyz/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/handlers.py
2016-07-28 16:42:51,199 - INFO - Received filetype completion available request
2016-07-28 16:43:24,306 - INFO - Received event notification
2016-07-28 16:43:24,308 - INFO - Received event notification
2016-07-28 16:43:24,310 - INFO - Received shutdown request
2016-07-28 16:43:24,417 - INFO - Stopping JediHTTP

**Comment by pass86** [comment]
@app.post( '/shutdown' )
def Shutdown():
  _logger.info( 'Received shutdown request' )
  ServerShutdown()

  return _JsonResponse( True )

def ServerShutdown():                                                                                                                                                                          
  def Terminator():
    if wsgi_server:
      wsgi_server.Shutdown()

  # Use a separate thread to let the server send the response before shutting
  # down.
  terminator = Thread( target = Terminator )
  terminator.daemon = True
  terminator.start()

I think StoppableWSGIServer is not thread safe.

**Comment by pass86** [comment]
handlers.wsgi_server = StoppableWSGIServer( handlers.app,
                                              host = args.host,
                                              port = args.port,                                                                                                                                
                                              threads = 30 )
  handlers.wsgi_server.Run()

**Comment by micbou** [comment]
> Sometimes shutdown do not finish.Python process and mono-sgen32 process is still is in Activity Monitor.

Could you open a new issue by following the instructions in [CONTRIBUTING.md](https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md#writing-good-issue-reports)? Also, could you give the associated commands of these two processes? I'd like to know if the Python process is the ycmd or JediHTTP one.

> I think StoppableWSGIServer is not thread safe.

Even if StoppableWSGIServer is not thread safe (which I doubt), this has nothing to do with your issue because the `Shutdown` method from `StoppableWSGIServer` is only executed by one thread (only one shutdown request was sent to the server).

**Comment by pass86** [comment]
Finally it quit a few minutes later, maybe it is waiting something.
