### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 333: invalid start byte

### ISSUE THREAD

**Issue by dubnde** [Valloric/ycmd#562]
I see the following error when trying completions in `c` code. This was working until I pulled latest tip last night and now it just doesn't play nicely. Using [emacs-ycmd](https://github.com/abingham/emacs-ycmd) client. 

I use [intercept-build](https://pypi.python.org/pypi/scan-build) to generate the compilation database

I can still jump to definitions no problem.

The error trace follows:

```

2016-07-27 10:27:07,653 - INFO - Adding buffer identifiers for file: 
/path/to/file.c
2016-07-27 10:27:15,269 - INFO - Received completion request
2016-07-27 10:27:15,269 - DEBUG - Using filetype completion: True
Traceback (most recent call last):
  File "/home/user/ycmd/third_party/bottle/bottle.py", line 996, in _inner_handle
    return route.call(**args)
  File "/home/user/ycmd/third_party/bottle/bottle.py", line 1954, in wrapper
    rv = callback(*a, **ka)
  File "/home/user/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "/home/user/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/user/ycmd/ycmd/../ycmd/handlers.py", line 100, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/user/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/user/ycmd/ycmd/../ycmd/completers/completer.py", line 234, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/user/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 115, in ComputeCandidatesInner
    return [ ConvertCompletionData( x ) for x in results ]
  File "/home/user/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 115, in <listcomp>
    return [ ConvertCompletionData( x ) for x in results ]
  File "/home/user/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 407, in ConvertCompletionData
    if completion_data.DocString() else None ) )
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 333: invalid start byte
```

**Comment by puremourning** [comment]
Thanks for reporting. Unfortunately to debug these issues we need a reproducible test case.

If you can send the contents of your file, then that would probably work, but at least we'll need some cutdown part that includes the unicode characters which are causing the problem.

**Comment by dubnde** [comment]
Sure. Thanks. Will need to reproduce it later on a small example as this happened on a sizeable commercial code base.

**Comment by dubnde** [comment]
Discarded old build. Pulled clean `ycmd `and rebuilt. Works now. 

```
mv $HOME/ycmd $HOME/ycmd.bk
git clone https://github.com/Valloric/ycmd.git $HOME/ycmd
cd $HOME/ycmd
git submodule update --init --recursive
python3 build.py --clang-complete
```

**Comment by dubnde** [comment]
Problem again. This looks to be related to the setting `(setq ycmd-force-semantic-completion t)`. Not exactly sure why I had it set in the first place. Got rid of it.

**Comment by ptrv** [comment]
I am wondering how the value of the variable `ycmd-force-semantic-completion` can be related to the unicode issue. When the variable is set to `t`, we only add `"force_semantic": true` to the request data to get semantic completion even without a semantic trigger.

**Comment by liugangnhm** [comment]
same issue after add `(setq ycmd-force-semantic-completion t)`
