### ISSUE TITLE
Frequent "Connection refused" errors from the HTTP server

### ISSUE THREAD

**Issue by pramodhegde** [Valloric/ycmd#574]

**Comment by pramodhegde** [comment]
Log says:
```
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
  File "/Users/phegde/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 548, in HandleFileParseRequest
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
    self._latest_diagnostics = self._latest_file_parse_request.Response()
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
  File "/Users/phegde/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/event_notification.py", line 65, in Response
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
    self._cached_response = JsonFromFuture( self._response_future )
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
  File "/Users/phegde/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 173, in JsonFromFuture
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
    response = future.result()
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
  File "/Users/phegde/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 397, in result
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
    return self.__get_result()
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
  File "/Users/phegde/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 356, in __get_result
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
    raise self._exception
Press ENTER or type command to continue
Error detected while processing function <SNR>72_OnCursorMovedNormalMode[5]..<SNR>72_OnFileReadyToParse:
line    9:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=53017): Max retries exceeded with url: /event_notification (Caused by NewConnectionError('<reque
sts.packages.urllib3.connection.HTTPConnection object at 0x10f5288d0>: Failed to establish a new connection: [Errno 61] Connection refused',))  
```

Seems to occur when the codebase tends to be a tad large.

**Comment by micbou** [comment]
Please, open the issue on [the YouCompleteMe repository](https://github.com/Valloric/YouCompleteMe) by following the instructions in [CONTRIBUTING.md](https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md).
