### ISSUE TITLE
Golang completion not working.

### ISSUE THREAD

**Issue by konkers** [Valloric/ycmd#607]
Getting this in the standard error logs:
```
2016-09-21 15:15:54,743 - ERROR - unknown encoding: 
Traceback (most recent call last):
  File "/Users/konkers/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/server_state.py", line 100, in FiletypeCompletionAvailable
    self.GetFiletypeCompleter( filetypes )
  File "/Users/konkers/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/server_state.py", line 83, in GetFiletypeCompleter
    for filetype in current_filetypes ]
  File "/Users/konkers/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/server_state.py", line 72, in _GetFiletypeCompleterForFiletype
    completer = module.GetCompleter( self._user_options )
  File "/Users/konkers/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/go/hook.py", line 33, in GetCompleter
    return GoCompleter( user_options )
  File "/Users/konkers/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/go/go_completer.py", line 123, in __init__
    self._StartServer()
  File "/Users/konkers/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/go/go_completer.py", line 226, in _StartServer
    with open( self._gocode_stdout, 'w' ) as stdout:
LookupError: unknown encoding: 
```

Based on #419 I changed to open()s to utils.OpenForStdHandle()s and it started working.  PR incomming.

**Comment by micbou** [comment]
Fixed by PR #608. Thanks again.
