### ISSUE TITLE
ERROR - No semantic completer exists for filetypes: [u'xml']

### ISSUE THREAD

**Issue by Orgil** [Valloric/ycmd#610]
i've been trying to run youcompleteme on typescript. But :YcmToggleLogs reported me below. I don't know why filetype is [u'xml']. i've checked file type vim reports it typescript.
```
ERROR - No semantic completer exists for filetypes: [u'xml']
Traceback (most recent call last):
  File "/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/server_state.py", line 100, in FiletypeCompletionAvailable
    self.GetFiletypeCompleter( filetypes )
  File "/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/server_state.py", line 90, in GetFiletypeCompleter
    current_filetypes ) )
```
i've set ft=typescript manually then completion started working.

**Comment by Orgil** [comment]
Somehow my plugins messed the file type. so closing this
