### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by moyotar** [Valloric/ycmd#646]
![image](https://cloud.githubusercontent.com/assets/22092607/20332813/7f917b50-abe9-11e6-9838-a70701258727.png)

I moved `ycmd` from windows 7 to windows 10. At first, it worked normally. Puzzlingly, I encountered this yesterday.

> python version: 2.7.6
> emacs: 24.5.1

**Comment by micbou** [comment]
Does the file `D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\urllib3\__init__.py` exists?

**Comment by moyotar** [comment]
Yes!
![image](https://cloud.githubusercontent.com/assets/22092607/20333601/85907286-abee-11e6-87e4-e782801c85b3.png)

**Comment by micbou** [comment]
I can't reproduce your issue on my Windows 10 64-bit VM with Python 2.7.6. I suggest you to do a clean install of YCM. If you don't get the issue anymore then you know it was caused by copying ycmd from one OS to another (could be the compiled bytecode files `*.pyc`).

**Comment by moyotar** [comment]
Oh, I think it's not a good solution. There's a wise way to make it?

**Comment by moyotar** [comment]
I deleted the `ycmd` and install it again.
![image](https://cloud.githubusercontent.com/assets/22092607/20388705/12b69b14-ad01-11e6-9758-51b4fed9ecb2.png)

However, I still got this error when I reopen my emacs.

**Comment by micbou** [comment]
Could you replace the following code in `D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\__init__.py`:
```python
try:
    from . import urllib3
except ImportError:
    import urllib3
    sys.modules['%s.urllib3' % __name__] = urllib3
```
by
```python
from . import urllib3
```
and then reproduce the issue so that we can see the actual `ImportError` traceback?

**Comment by moyotar** [comment]
```
Traceback (most recent call last):
  File "d:\app\emacs\extraBin\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\app\emacs\extraBin\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\app\emacs\extraBin\ycmd\ycmd\__main__.py", line 45, in <module>
    from ycmd.hmac_plugin import HmacPlugin
  File "D:\app\emacs\extraBin\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 27, in <module>
    import requests
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\__init__.py", line 58, in <module>
    from . import utils
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\compat.py", line 7, in <module>
    from .packages import chardet
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\__init__.py", line 26, in <module>
    from . import urllib3
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\urllib3\connectionpool.py", line 35, in <module>
    from .connection import (
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\urllib3\connection.py", line 43, in <module>
    from .util.ssl_ import (
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\urllib3\util\__init__.py", line 6, in <module>
    from .ssl_ import (
  File "D:\app\emacs\extraBin\ycmd\third_party\requests\requests\packages\urllib3\util\ssl_.py", line 4, in <module>
    import hmac
  File "d:\app\emacs\extraBin\Python27\lib\hmac.py", line 8, in <module>
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest

```

After replacing, I got this.

**Comment by micbou** [comment]
According to [this SO post](http://stackoverflow.com/a/26550917), your Python 2 installation is probably corrupted. Do you have multiple versions of Python 2 installed on your machine? Could you try to remove all of them and reinstall Python 2.7.6 (or even better install the last version 2.7.12)?

**Comment by moyotar** [comment]
Awesome! Thanks a lot! After deleting all the python version in my machine, I reinstalled python and ycmd.
Now, ycmd works normally again! Thanks!
