### ISSUE TITLE
Shutdown tests are failing for some reason

### ISSUE THREAD

**Issue by onur** [Valloric/ycmd#670]
Hi. I am maintainer of vim-youcompleteme/ycmd packages for Debian and Ubuntu. I am making an updated version of packages before sid freezes but `ycmd.tests.shutdown_test.Shutdown_test` started giving errors for an unknown reason and there isn't much output other than: `<h1>Critical error while processing request: /ready</h1>`.

I hope you can tell the actual reason I can't figure out myself and all tests must pass before this package get into Debian.

All other tests are working fine (ignore `GetCompletions_UnicodeInLineFilter_test` for now).

Output of `./run_tests.py`:

```
$ HOME=«PKGBUILDDIR» LC_ALL=C.UTF-8 ./run_tests.py --skip-build --no-byte-compile --exclude='^cs$' --exclude='UnknownExtraConfException' --exclude='javascript' --exclude='rust' --exclude='go' --exclude='AddNearestThirdPartyFoldersToSysPath_'
...
#63 ycmd.tests.clang.get_completions_test.GetCompletions_UnicodeInLineFilter_test ... FAIL
...
#349 ycmd.tests.shutdown_test.Shutdown_test.FromHandlerWithSubservers_test ... ERROR
#350 ycmd.tests.shutdown_test.Shutdown_test.FromHandlerWithoutSubserver_test ... ERROR
#351 ycmd.tests.shutdown_test.Shutdown_test.FromWatchdogWithSubservers_test ... ERROR
#352 ycmd.tests.shutdown_test.Shutdown_test.FromWatchdogWithoutSubserver_test ... ERROR
...

======================================================================
ERROR: ycmd.tests.shutdown_test.Shutdown_test.FromHandlerWithSubservers_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 268, in Wrapper
    test( self, *args )
  File "«PKGBUILDDIR»/ycmd/tests/shutdown_test.py", line 47, in FromHandlerWithSubservers_test
    self.Start()
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 123, in Start
    self._WaitUntilReady()
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 145, in _WaitUntilReady
    if self._IsReady( filetype ):
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 131, in _IsReady
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:43069/ready
-------------------- >> begin captured stdout << ---------------------
Logfile /tmp/server_43069_stdout_6eJ9SK.log:

serving on http://localhost:43069

Logfile /tmp/server_43069_stderr_7AGncR.log:

2016-12-20 17:59:37,210 - DEBUG - No global extra conf, not calling method YcmCorePreload
2016-12-20 17:59:37,288 - INFO - Received ready request
<h1>Critical error while processing request: /ready</h1>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: http://127.0.0.1:43069 "GET /ready HTTP/1.1" 500 56
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: ycmd.tests.shutdown_test.Shutdown_test.FromHandlerWithoutSubserver_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 268, in Wrapper
    test( self, *args )
  File "«PKGBUILDDIR»/ycmd/tests/shutdown_test.py", line 35, in FromHandlerWithoutSubserver_test
    self.Start()
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 123, in Start
    self._WaitUntilReady()
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 145, in _WaitUntilReady
    if self._IsReady( filetype ):
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 131, in _IsReady
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:54981/ready
-------------------- >> begin captured stdout << ---------------------
Logfile /tmp/server_54981_stdout_faODoI.log:

serving on http://localhost:54981

Logfile /tmp/server_54981_stderr_6eWRjf.log:

2016-12-20 17:59:37,627 - DEBUG - No global extra conf, not calling method YcmCorePreload
2016-12-20 17:59:37,701 - INFO - Received ready request
<h1>Critical error while processing request: /ready</h1>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: http://127.0.0.1:54981 "GET /ready HTTP/1.1" 500 56
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: ycmd.tests.shutdown_test.Shutdown_test.FromWatchdogWithSubservers_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 268, in Wrapper
    test( self, *args )
  File "«PKGBUILDDIR»/ycmd/tests/shutdown_test.py", line 77, in FromWatchdogWithSubservers_test
    self.Start( idle_suicide_seconds = 5, check_interval_seconds = 1 )
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 123, in Start
    self._WaitUntilReady()
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 145, in _WaitUntilReady
    if self._IsReady( filetype ):
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 131, in _IsReady
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:48569/ready
-------------------- >> begin captured stdout << ---------------------
Logfile /tmp/server_48569_stdout_Yivous.log:

serving on http://localhost:48569

Logfile /tmp/server_48569_stderr_hEKvBO.log:

2016-12-20 17:59:38,038 - DEBUG - No global extra conf, not calling method YcmCorePreload
2016-12-20 17:59:38,114 - INFO - Received ready request
<h1>Critical error while processing request: /ready</h1>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: http://127.0.0.1:48569 "GET /ready HTTP/1.1" 500 56
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: ycmd.tests.shutdown_test.Shutdown_test.FromWatchdogWithoutSubserver_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 268, in Wrapper
    test( self, *args )
  File "«PKGBUILDDIR»/ycmd/tests/shutdown_test.py", line 68, in FromWatchdogWithoutSubserver_test
    self.Start( idle_suicide_seconds = 2, check_interval_seconds = 1 )
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 123, in Start
    self._WaitUntilReady()
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 145, in _WaitUntilReady
    if self._IsReady( filetype ):
  File "«PKGBUILDDIR»/ycmd/tests/client_test.py", line 131, in _IsReady
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:46765/ready
-------------------- >> begin captured stdout << ---------------------
Logfile /tmp/server_46765_stdout_jTSSbX.log:

serving on http://localhost:46765

Logfile /tmp/server_46765_stderr_AUSJth.log:

2016-12-20 17:59:38,451 - DEBUG - No global extra conf, not calling method YcmCorePreload
2016-12-20 17:59:38,527 - INFO - Received ready request
<h1>Critical error while processing request: /ready</h1>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
requests.packages.urllib3.connectionpool: DEBUG: http://127.0.0.1:46765 "GET /ready HTTP/1.1" 500 56
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: ycmd.tests.clang.get_completions_test.GetCompletions_UnicodeInLineFilter_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "«PKGBUILDDIR»/ycmd/tests/test_utils.py", line 292, in Wrapper
    raise test_exception
AssertionError: 
Expected: a dictionary containing {u'errors': an empty collection, u'completions': a sequence over [a dictionary containing {u'insertion_text': u'member_with_\xe5_unic\xf8de', u'extra_menu_info': u'int'}] in any order, u'completion_start_column': <8>}
     but: value for u'completions' no item matches: a dictionary containing {u'insertion_text': u'member_with_\xe5_unic\xf8de', u'extra_menu_info': u'int'} in []

-------------------- >> begin captured stdout << ---------------------
Completer response: {
  "errors": [], 
  "completions": [], 
  "completion_start_column": 8
}
Test failed for the wrong reason: Traceback (most recent call last):
  File "«PKGBUILDDIR»/ycmd/tests/test_utils.py", line 285, in Wrapper
    assert_that( test_exception_message, matcher )
  File "/usr/lib/python2.7/dist-packages/hamcrest/core/assert_that.py", line 42, in assert_that
    _assert_match(actual=arg1, matcher=arg2, reason=arg3)
  File "/usr/lib/python2.7/dist-packages/hamcrest/core/assert_that.py", line 56, in _assert_match
    raise AssertionError(str(description))
AssertionError: 
Expected: a string containing u"value for 'completions' no item matches"
     but: was "\nExpected: a dictionary containing {u'errors': an empty collection, u'completions': a sequence over [a dictionary containing {u'insertion_text': u'member_with_\\xe5_unic\\xf8de', u'extra_menu_info': u'int'}] in any order, u'completion_start_column': <8>}\n     but: value for u'completions' no item matches: a dictionary containing {u'insertion_text': u'member_with_\\xe5_unic\\xf8de', u'extra_menu_info': u'int'} in []\n"



--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
ycmd.handlers: INFO: Received extra conf load request
ycmd.handlers: INFO: Received event notification
ycmd.handlers: DEBUG: Event name: FileReadyToParse
ycmd.completers.all.identifier_completer: INFO: Adding buffer identifiers for file: «PKGBUILDDIR»/ycmd/tests/clang/testdata/unicode.cc
ycmd.handlers: INFO: Received completion request
ycmd.handlers: DEBUG: Using filetype completion: True
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 723 tests in 7.129s

FAILED (SKIP=19, errors=4, failures=1)
Running tests on Python 2.7.13
Running flake8
Traceback (most recent call last):
  File "./run_tests.py", line 227, in <module>
    Main()
  File "./run_tests.py", line 224, in Main
    NoseTests( parsed_args, nosetests_args )
  File "./run_tests.py", line 212, in NoseTests
    subprocess.check_call( [ 'nosetests' ] + nosetests_args )
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'nosetests', u'-v', u'--with-id', '--no-byte-compile', '--exclude=^cs$', '--exclude=UnknownExtraConfException', '--exclude=javascript', '--exclude=rust', '--exclude=go', '--exclude=AddNearestThirdPartyFoldersToSysPath_']' returned non-zero exit status 1
debian/rules:40: recipe for target 'override_dh_auto_test' failed
make: *** [override_dh_auto_test] Error 1

```

You can also see unstripped log and build log in attached files:

[01-tests-nocapture.txt](https://github.com/Valloric/ycmd/files/664032/01-tests-nocapture.txt)
[02-build.txt](https://github.com/Valloric/ycmd/files/664034/02-build.txt)

**Comment by micbou** [comment]
This looks like [an issue with Bottle](https://github.com/bottlepy/bottle/blob/master/bottle.py#L1098) but I can't reproduce with the last version (0.12.11) so it's maybe something else. Could you enable [Bottle debug mode](https://bottlepy.org/docs/dev/tutorial.html#debug-mode) and run again the tests?

**Comment by micbou** [comment]
Add the line:
```python
bottle.debug(True)
```
at [the top of `ycmd/handlers.py`](https://github.com/Valloric/ycmd/blob/master/ycmd/handlers.py#L45).

**Comment by onur** [comment]
Got more output:

```html
<h1>Critical error while processing request: /ready</h1><h2>Error:</h2>
<pre>
AssertionError(&quot;Header value &#039;GnTUG+4AtoG0wa/zAUZLXwOTvpJQV52eNMpfC06RQMY=&#039; is not a string in (&#039;X-Ycm-Hmac&#039;, &#039;GnTUG+4AtoG0wa/zAUZLXwOTvpJQV52eNMpfC06RQMY=&#039;)&quot;,)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/dist-packages/bottle.py&quot;, line 960, in wsgi
    start_response(response._status_line, response.headerlist)
  File &quot;/usr/lib/python2.7/dist-packages/waitress/task.py&quot;, line 375, in start_response
    &#039;Header value %r is not a string in %r&#039; % (v, (k, v))
AssertionError: Header value &#039;GnTUG+4AtoG0wa/zAUZLXwOTvpJQV52eNMpfC06RQMY=&#039; is not a string in (&#039;X-Ycm-Hmac&#039;, &#039;GnTUG+4AtoG0wa/zAUZLXwOTvpJQV52eNMpfC06RQMY=&#039;)

</pre>
```

**Comment by onur** [comment]
Versions of modules used on build:

```
python2.7: 2.7.13-1
python-bottle: 0.12.11-1
python-dev: 2.7.11-2
python-future: 0.15.2-4
python-frozendict: 0.5-1
python-hamcrest: 1.8.0-1
python-jedi: 0.9.0-1
python-mock: 2.0.0-3
python-nose: 1.3.7-2
python-pep8: 1.7.0-4
python-psutil: 5.0.0-1
python-requests: 2.12.4-1
python-setuptools: 32.0.0-1
python-waitress: 1.0.1-1
python-webtest: 2.0.23-1
```

**Comment by onur** [comment]
Ok I have more information. ycmd is actually returning same response for every request and ycmd is only working with bottle that comes with ycmd.

I tried bottle 0.8, 0.12.11 and master, getting same error all the time. To reproduce this just update bottle submodule in third_party directory and try to run ycmd with latest bottle.
