### ISSUE TITLE
TypeError: Key must be a buffer

### ISSUE THREAD

**Issue by Al-Nibras** [Valloric/ycmd#801]
> TypeError: Key must be a buffer
	at new Hmac (crypto.js:91:16)
	at Object.Hmac (crypto.js:89:12)
	at generateHmac (/Users/al-nibras/.atom/packages/you-complete-me/lib/handler.coffee:102:12)
	at signMessage (/Users/al-nibras/.atom/packages/you-complete-me/lib/handler.coffee:113:65)
	at /Users/al-nibras/.atom/packages/you-complete-me/lib/handler.coffee:164:7

I get this message when I start Atom. I've installed ycmd and Atom plugin "you-complete-me". My `extra_conf_store.py` is like the file below:
https://github.com/puremourning/ycmd-1/blob/c74044309effa759960031288a7dec659fd6fea9/ycmd/default_ycm_extra_conf.py

I use it primary for C language. And to be certain, for cross-compiling C (Kernel Development stuff)

**Comment by puremourning** [comment]
Could you raise it with the guys who make the atom plugin? Looks like an issue there rather than with ycmd
