### ISSUE TITLE
YouCompleteMe unavailable: 'encoding' is an invalid keyword argument

### ISSUE THREAD

**Issue by sygi** [Valloric/ycmd#817]
I got an error after installing YouCompleteMe that seems to be within ycmd. As far as I understand, the 
[open](https://github.com/Valloric/ycmd/blob/master/ycmd/utils.py#L58) call assumes it is executed in python3, but for some reason it is called by python2 here. Full error:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "XXX/ycm/setup.py", line 49, in SetUp
YCM
    base.LoadJsonDefaultsIntoVim()
  File "XXX/ycm/base.py", line 52, in LoadJs
onDefaultsIntoVim
    defaults = user_options_store.DefaultOptions()
  File "XXX/ycmd/ycmd/user_options
_store.py", line 50, in DefaultOptions
    options = json.loads( ReadFile( settings_path ) )
  File "XXX/ycmd/ycmd/utils.py", l
ine 58, in ReadFile
    with open( filepath, encoding = 'utf8' ) as f:
TypeError: 'encoding' is an invalid keyword argument for this function    
```

Could we substitute this (and subsequence) calls to [io.open](https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data), so that both pythons are supported?

Thank you

**Comment by micbou** [comment]
Could be the same issue as https://github.com/Valloric/YouCompleteMe/issues/2262 (which was caused by a conflict with the flake8-vim plugin). To know if that's the case, could you paste the output of the command
```viml
:py import pprint; pprint.pprint( sys.path )
```
in Vim?

**Comment by sygi** [comment]
Thanks for taking a look at this. It doesn't seem I have flake8-vim:

```
[u'/usr/lib/youcompleteme/third_party/ycmd/third_party/JediHTTP',
 u'/usr/lib/youcompleteme/third_party/ycmd/third_party/waitress',
 u'/usr/lib/youcompleteme/third_party/ycmd/third_party/requests',
 u'/usr/lib/youcompleteme/third_party/ycmd/third_party/bottle',
 u'/usr/lib/youcompleteme/third_party/ycmd/third_party/frozendict',
 u'/usr/lib/youcompleteme/third_party/ycmd',
 u'/usr/lib/youcompleteme/third_party/requests_futures',
 u'/usr/lib/youcompleteme/third_party/futures',
 u'/usr/lib/youcompleteme/python/ycm/../../third_party/ycmd',
 u'/usr/lib/youcompleteme/autoload/../python',
 '/usr/local/lib/python2.7/dist-packages/frosted-1.4.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pies-2.6.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/enum34-1.1.6-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pies2overrides-2.6.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/ipaddress-1.0.18-py2.7.egg',
 '/usr/local/buildtools/current/sitecustomize',
 '/usr/lib/python2.7',
 u'/usr/lib/youcompleteme/third_party/ycmd/third_party/python-future/src',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/google/home/sygi/.local/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '_vim_path_']
```

**Comment by micbou** [comment]
Those lines:
```
'/usr/local/lib/python2.7/dist-packages/pies-2.6.7-py2.7.egg',
'/usr/local/lib/python2.7/dist-packages/pies2overrides-2.6.7-py2.7.egg',
```
in the Python path are probably causing the issue. [Pies](https://github.com/timothycrosley/deprecated.pies) and [python-future](https://github.com/PythonCharmers/python-future) conflict with each other; the latter being used by YCM for Python 2 and 3 compatibility.

We need to know where those paths
```
 '/usr/local/lib/python2.7/dist-packages/frosted-1.4.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pies-2.6.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/enum34-1.1.6-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pies2overrides-2.6.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/ipaddress-1.0.18-py2.7.egg',
```
come from. What's the value of the `PYTHONPATH` environment variable
```viml
:echo $PYTHONPATH
```
?

**Comment by sygi** [comment]
I remember installing frosted myself. It seems that it depends on pies:
https://pypi.python.org/pypi/frosted/1.4.1. I assume that the workaround is
to remove frosted?

**Comment by micbou** [comment]
Yes, that should work. You could replace it with [pyflakes](https://github.com/PyCQA/pyflakes). Frosted doesn't seem to be actively maintained.

**Comment by sygi** [comment]
Ok, thank you for the help.
