### ISSUE TITLE
how can I export a specific libc.so.6 for ycm_core.so

### ISSUE THREAD

**Issue by AoZhang** [Valloric/ycmd#838]
I install YouCompleteMe with the following commands:
```
$ cd ~/.vim/bundle/YouCompleteMe
$ export PATH=/path/to/gcc-4.8.2/bin:$PATH
$ ./install.py --clang-completer
```
And it seems that everything goes ok. when I'm trying to edit a python file, some error happens:

```
ERROR - /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /.../YouCompleteMe/third_party/ycmd/ycmd/../ycm_core.so)
Traceback (most recent call last):
  File "/.../YouCompleteMe/third_party/ycmd/ycmd/server_utils.py", line 96, in CompatibleWithCurrentCore
    ycm_core = ImportCore()
  File "/.../YouCompleteMe/third_party/ycmd/ycmd/server_utils.py", line 88, in ImportCore
    import ycm_core as ycm_core
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /.../YouCompleteMe/third_party/ycmd/ycmd/../ycm_core.so)
```

I'm using CentOS 6.3, and the version of the default glibc is 2.12.

If I set LD_LIBRARY_PATH to the path of /path/to/gcc-4.8.2/lib, it becomes worse.
```
$ LD_LIBRARY_PATH=/path/to/gcc-4.8.2/lib vim a.py
[1]    40437 segmentation fault  LD_LIBRARY_PATH=/path/to/gcc-4.8.2/lib vim a.py
``` 

Can I setting the specific glibc only for ycm_core.so? thanks.

**Comment by micbou** [comment]
You need a more recent version of glibc. Did you see this message:
> In order to use this application, you require a more modern compiler than the default compiler on this platform. Please install the devtoolset-6 or greater. For example, see this link: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/

when running the `install.py` script without adding a newer GCC to `PATH`?

**Comment by AoZhang** [comment]
I've added the gcc 4.8.2 to the PATH before running `install.py`. The error happens while I'm coding in vim.

And I have no permission to install any dev-tool into the system pathes.

**Comment by micbou** [comment]
> I've added the gcc 4.8.2 to the PATH before running install.py. The error happens while I'm coding in vim.

So, when running `install.py` for the first time, you didn't see the message I mentioned (that tells the user to install devtoolset-6)? Did you only see the error:
```
Your C++ compiler does NOT fully support C++11.
```
?

**Comment by AoZhang** [comment]
I got no errors when running `install.py`. here's all the log:
```
Searching Python 2.7 libraries...
Found Python library: /path/to/lib/python2.7/config/libpython2.7.so
Found Python headers folder: /path/to/include/python2.7
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /path/to/gcc-4.8.2/bin/cc
-- Check for working C compiler: /path/to/gcc-4.8.2/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /path/to/gcc-4.8.2/bin/c++
-- Check for working CXX compiler: /path/to/gcc-4.8.2/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /path/to/lib/python2.7/config/libpython2.7.so (found suitable version "2.7.3", minimum required is "2.6")
Using Clang archive: /path/to/YouCompleteMe/third_party/ycmd/cpp/../clang_archives/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
Using libclang to provide semantic completion for C/C++/ObjC
Using external libclang: /tmp/ycm_build_tzfqXA/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/lib/libclang.so.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ycm_build_tzfqXA
Scanning dependencies of target BoostParts
[  2%] [  2%] [  4%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/winstances.cpp.o
Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/static_mutex.cpp.o
[  5%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/regex.cpp.o
Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/instances.cpp.o
[  6%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/c_regex_traits.cpp.o
[  8%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/icu.cpp.o
[  9%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/regex_raw_buffer.cpp.o
...
...
...
[ 95%] Building CXX object ycm/CMakeFiles/ycm_core.dir/PythonSupport.cpp.o
[ 97%] Building CXX object ycm/CMakeFiles/ycm_core.dir/LetterNodeListMap.cpp.o
[ 98%] Building CXX object ycm/CMakeFiles/ycm_core.dir/LetterNode.cpp.o
[100%] Building CXX object ycm/CMakeFiles/ycm_core.dir/IdentifierDatabase.cpp.o
Linking CXX shared library /path/to/YouCompleteMe/third_party/ycmd/ycm_core.so
[100%] Built target ycm_core
```

**Comment by puremourning** [comment]
How did you install gcc? Our wiki has a guide for centos 6 and we recommend dev-toolset 6 as the red hat supported toolchain.

**Comment by AoZhang** [comment]
> How did you install gcc?
the gcc4.8.2 was installed by the system administrator, which contains all the tool-chain, like g++, ld, ar and so on.

**Comment by micbou** [comment]
What happens if you go to the `~/.vim/bundle/YouCompleteMe/third_party/ycmd` folder and run the command:
```sh
LD_LIBRARY_PATH=/path/to/gcc-4.8.2/lib python -c "import ycm_core; print(ycm_core.HasClangSupport())
```
? It should return `True`.

**Comment by davits** [comment]
Another way is to create symlinks in your ycmd directory.
For example: libgcc_s.so.1 -> /path_to_gcc/gcc-5.2.0/lib64/libgcc_s.so.1
Also run ldd ycm_core.so and see if any of the dependent libraries is resolved incorrectly.

**Comment by AoZhang** [comment]
@micbou :
after running the command
> LD_LIBRARY_PATH=/path/to/gcc-4.8.2/lib python -c "import ycm_core; print(ycm_core.HasClangSupport())

I got a segmentation fault, because the python which I'm using is compiled by the system gcc(4.4.6).
```
[1]    61183 segmentation fault  LD_LIBRARY_PATH=/path/to/gcc-4.8.2/lib python -c
```

**Comment by AoZhang** [comment]
@davits 
I create some symlinks, but it seams that it has no help to me. here's the `ldd` result
```
$ ldd ycm_core.so
    linux-vdso.so.1 =>  (0x00007fff9cdff000)
    libpython2.7.so.1.0 => not found
    librt.so.1 => /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/./librt.so.1 (0x00007f0a4ec12000)
    libstdc++.so.6 => /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/./libstdc++.so.6 (0x00007f0a4e90f000)
    libm.so.6 => /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/./libm.so.6 (0x00007f0a4e60b000)
    libgcc_s.so.1 => /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/./libgcc_s.so.1 (0x00007f0a4e3f5000)
    libc.so.6 => /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/./libc.so.6 (0x00007f0a4e048000)
    libpthread.so.0 => /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/./libpthread.so.0 (0x00007f0a4de29000)
    /lib64/ld-linux-x86-64.so.2 (0x000000318a600000)
```

**Comment by micbou** [comment]
You may have to recompile Python with your version of GCC. Anyway, the issue tracker is not for technical support.
