### ISSUE TITLE
Rust completion Server Error from racerd

### ISSUE THREAD

**Issue by noxdafox** [Valloric/ycmd#849]
Greetings,

I am running Ycmd with emacs. Ycmd and emacs-ycmd are up to date.

Tried both rust from Debian package (version 1.19) and from the official installer (version 1.20).

The rust source is correctly installed via `rustup`.

This is the ycmd output.

```2017-09-29 23:29:32,263 - DEBUG - Making racerd request: b'POST' b'http://127.0.0.1:35895/list_completions' {'content-type': 'application/json', 'x-racerd-hmac': b'c5f033ec21a2398609e57083975edabd758d8fc050f1fc14a687f51b7a0652cc'} b'{"line": 2, "buffers": [{"contents": "fn main() {\\n    printo\\n}\\n", "file_path": "/home/noxdafox/development/rlips/repl.rs"}], "column": 10, "file_path": "/home/noxdafox/development/rlips/repl.rs"}'
2017-09-29 23:29:32,263 - INFO - Starting new HTTP connection (1): 127.0.0.1
2017-09-29 23:29:32,264 - DEBUG - "POST /list_completions HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/home/noxdafox/development/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/noxdafox/development/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/completers/completer.py", line 218, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/completers/completer.py", line 231, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 264, in ComputeCandidatesInner
    completions = self._FetchCompletions( request_data )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 282, in _FetchCompletions
    return self._GetResponse( '/list_completions', request_data )
  File "/home/noxdafox/development/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 198, in _GetResponse
    response.raise_for_status()
  File "/home/noxdafox/development/ycmd/third_party/requests/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:35895/list_completions
```

 Is there a way I can get the racerd logs? That would help clarifying the issue.

**Comment by noxdafox** [comment]
Found an issue which could be related: https://github.com/abingham/emacs-ycmd/issues/354

**Comment by micbou** [comment]
Run the `ycmd-show-debug-info` command while editing a Rust file. You'll find the paths to the racerd logfiles on the line:
```elisp
(completer (servers ((logfiles
```
By the way, could you paste the full output of the command here?

**Comment by noxdafox** [comment]
That's a good tip thanks! Did not expect logs to end up in `/tmp`

Racerd output:

```
Ycmd debug information for buffer ast.rs in rust-mode:


((python (version . "3.5.3") (executable . "/usr/bin/python3"))
 (completer (items ((value . "/home/noxdafox/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src")
                    (key . "Rust sources")))
            (name . "Rust")
            (servers ((address . "127.0.0.1")
                      (pid . 9966)
                      (logfiles "/tmp/racerd_35895_stdout_ex_wnbl0.log"
                                "/tmp/racerd_35895_stderr_hhmzo84l.log")
                      (is_running . t)
                      (extras)
                      (port . 35895)
                      (name . "Racerd")
                      (executable . "/home/noxdafox/development/ycmd/third_party/racerd/target/release/racerd"))))
 (extra_conf (is_loaded . t)
             (path . "/home/noxdafox/.emacs.d/ycmd_global_config.py"))
 (clang (has_support . t)
        (version . "clang version 3.8.1-24 (tags/RELEASE_381/final)")))


Server is running at: 127.0.0.1:40883

Ycmd Mode is enabled

--------------------

Ycmd version:   1.3snapshot (package: 20170926.2252)
Emacs version:  25.2.2
System:         x86_64-pc-linux-gnu
Window system:  x
```

Logs are full of these messages:

```
ERROR:iron::iron: Error handling:
Request {
    url: Url { generic_url: "http://127.0.0.1:35895/list_completions" }
    method: Post
    remote_addr: V4(127.0.0.1:41090)
    local_addr: V4(127.0.0.1:35895)
}
Error was: Error { repr: Custom(Custom { kind: Other, error: NotSupported }) }
```

**Comment by micbou** [comment]
Thanks. I think you are experiencing issue https://github.com/jwilm/racerd/issues/45.

**Comment by noxdafox** [comment]
Yes I was suspecting it was related as the issue https://github.com/abingham/emacs-ycmd/issues/354 points towards the same direction. Is there any available workaround?

**Comment by micbou** [comment]
You could try to apply the changes in PR https://github.com/jwilm/racerd/pull/63 (only the changes in `Cargo.toml` and `src/http/mod.rs` are needed) then recompile racerd with the command:
```
cargo build --release
```

**Comment by noxdafox** [comment]
Applying the changes fixed the issue. Thanks!

I guess it's better to keep the ticket open until the issue is not fixed upstream.

**Comment by bstaletic** [comment]
We have migrated to RLS. Closing.
