### ISSUE TITLE
In deepin Linux (based on Debian) doesn't auto complete c/c++ while in Manjaro ycmd does work

### ISSUE THREAD

**Issue by tengyft** [Valloric/ycmd#879]
In Deepin linux which is based on Debian, ycmd does not auto complete c/c++ source code. But in Manjaro, ycmd can work well. I want to know why. How to fix it.

**Comment by bstaletic** [comment]
Can you post ycmd and the client logs?

**Comment by tengyft** [comment]
2017-11-30 14:32:25,282 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:35575
2017-11-30 14:32:25,340 - INFO - Received event notification
2017-11-30 14:32:25,340 - DEBUG - Event name: BufferVisit
2017-11-30 14:32:25,405 - INFO - Received event notification
2017-11-30 14:32:25,405 - DEBUG - Event name: FileReadyToParse
2017-11-30 14:32:25,406 - INFO - Adding buffer identifiers for file: /home/tengyft/hello.cpp
2017-11-30 14:32:25,407 - INFO - /home/tengyft/.emacs.d/layers/+tools/ycmd/global_conf.py: Getting flags for /home/tengyft/hello.cpp
2017-11-30 14:32:25,407 - INFO - hello.cpp: Could not get compilation flags from db: could not find compile_commands.json
2017-11-30 14:32:25,407 - INFO - hello.cpp: No extra flags.
2017-11-30 14:32:25,408 - ERROR - hello.cpp: No flags were found !
Traceback (most recent call last):
  File "/opt/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/opt/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/opt/ycmd/ycmd/../ycmd/handlers.py", line 70, in EventNotification
    event_handler )( request_data )
  File "/opt/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 387, in OnFileReadyToParse
    raise ValueError( NO_COMPILE_FLAGS_MESSAGE )
ValueError: Still no compile flags, no completions yet.


Here is my spacemacs ycmd-server log, I did not generate the .ycm_extra_conf.py, when in Manjaro, the spacemacs can auto complete such as namespace, functions etc for me. But in Deepin, spacemacs just auto complete the project functions when there is a generated .ycm_extra_conf.py.

**Comment by bstaletic** [comment]
> Still no compile flags, no completions yet.

You always need a `.ycm_extra_config.py`.

As you don't have any `.ycm_extra_conf.py` you can't have completions. Manjro probably provided a default one somehow. Check with `:YcmDebugInfo`.
