### ISSUE TITLE
Java test failure: ServerManagement_ProjectDetection_GradleParent_test

### ISSUE THREAD

**Issue by orsonteodoro** [Valloric/ycmd#944]
All java test work except this one and ycmd.tests.java.server_management_test.ServerManagement_RestartServer_test.  I am using openjdk8 (openjdk8-8.151.12) on Alpine Linux Edge. 

export JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk/"
run_tests.py --skip-build --completers python cs cfamily go javascript java rust typescript

<pre>
#225 ycmd.tests.java.server_management_test.ServerManagement_ProjectDetection_GradleParent_test ... Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/orson/aports-me3/aports/testing/py-ycmd/src/ycmd-f260d2e1fcddd33fb319abfd277fe169108750e3_python2/ycmd/tests/java/diagnostics_test.py", line 369, in PollForMessagesInAnotherThread
    'contents': contents } ):
  File "/home/orson/aports-me3/aports/testing/py-ycmd/src/ycmd-f260d2e1fcddd33fb319abfd277fe169108750e3_python2/ycmd/tests/java/__init__.py", line 120, in PollForMessages
    timeout ) )
PollForMessagesTimeoutException: Waited for diagnostics to be ready for 30 seconds, aborting.

ok
#226 ycmd.tests.java.server_management_test.ServerManagement_ProjectDetection_MavenParent_test ... ok
</pre>

Full log: https://gist.github.com/orsonteodoro/8504073bf2f53f2bc5f7dc009a70c7b4

**Comment by puremourning** [comment]
Is that the right link?

I can see no indication that you even enabled the java completer

n
> ycmd.completers.java.java_completer: WARNING: Not using java completion: jdt.ls is not installed

**Comment by puremourning** [comment]
Also for my information why is this causing you an issue? Are you working on a ycmd change

**Comment by orsonteodoro** [comment]
I updated the log.  It seemed to OK at the end or says ok for that individual test.  I thought it was the source of failure but it was caused by py-jedi not being added as a check dependency.   I will close this unless you think the exception is not acceptable.

I am trying to package this for Alpine Linux.  I was either thinking enable the java completer or disable it based on this traceback.  I will leave it enabled since it is ok.

I just got this also, but it is just random:
<pre>
#226 ycmd.tests.java.server_management_test.ServerManagement_ProjectDetection_MavenParent_test ... ok
#227 ycmd.tests.java.server_management_test.ServerManagement_CloseServer_Unclean_test ... Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/orson/aports-me3/aports/testing/py-ycmd/src/ycmd-f260d2e1fcddd33fb319abfd277fe169108750e3_python2/ycmd/tests/java/diagnostics_test.py", line 369, in PollForMessagesInAnotherThread
    'contents': contents } ):
  File "/home/orson/aports-me3/aports/testing/py-ycmd/src/ycmd-f260d2e1fcddd33fb319abfd277fe169108750e3_python2/ycmd/tests/java/__init__.py", line 120, in PollForMessages
    timeout ) )
PollForMessagesTimeoutException: Waited for diagnostics to be ready for 30 seconds, aborting.

ok
#228 ycmd.tests.java.server_management_test.ServerManagement_ConnectionRaisesWhileShuttingDown_test ... ok
#229 ycmd.tests.java.server_management_test.ServerManagement_ProjectDetection_EclipseParent_test ... ok
<pre>

**Comment by puremourning** [comment]
per the YCM docs, java support is experimental
